server:
  port: 8081
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: none

spring:
  config:
    import:
      - dataSource.yml